services:
  backend:
    build:
      context: .  # This points to the parent directory of the /dev folder
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge